language: python
cache: pip
python:
  - "3.6"

install:
  - cd boussole
  - pip install -r requirements.txt
  
before_deploy:
  - cd boussole
  - python manage.py collectstatic --noinput

deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  region: "$AWS_REGION"  
  app: "$EB_APPNAME"
  env: "$EB_ENVNAME"
  bucket_name: "$EB_BUCKET"

