# Generated by Django 2.0.6 on 2018-07-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
